### ISSUE TITLE
Will this be available within the IDE?

### ISSUE THREAD

**Issue by ff6347** [fathominfo/processing-p5js-mode#1]
Or only as manual download and install? I'm in a similar position as you. I need something to teach P5.js with but the official P5.app is not reliable.

**Comment by benfry** [comment]
It'll be in the IDE, I just need to finish Library imports and it'll be posted along with Processing 3.2.

**Comment by ff6347** [comment]
awesome. Thanks.

**Comment by q2dg** [comment]
Why "this project will have a lifespan of just a few months" (from README.md) ?? It's awesome...go with it!!
