### ISSUE TITLE
p5.js mode fails to install in Processing PDE, install always incomplete

### ISSUE THREAD

**Issue by lmccart** [fathominfo/processing-p5js-mode#11]
moving post from @jeremydouglass https://github.com/processing/p5.js/issues/1600:

I'm using Processing PDE 3.2.1 on OS X 10.10.5.
1. When I go to "Modes" to add p5.js, it says that p5.js 1.0.2 is available.
2. When I install p5.js, however, it now says 1.0 is installed, an update to 1.0.2 is available.
3. When I update to 1.0.2:  
   a. ...using the Modes tab, it downloads, installs, and then again says 1.0 is installed and 1.0.2 is available.  
   b. ...using the Updates tab / "Update All", it spins and times out.

https://forum.processing.org/two/discussion/18248/p5-js-mode-fails-to-update-install-always-incomplete

**Comment by benfry** [comment]
From @prisonerjohn, the reason for this one: 

> I just tried updating the p5js Mode to 1.0.2 but it's silently failing because the properties file inside the zip still lists the version as 1/1.0. Remember that https://github.com/fathominfo/processing-p5js-mode/releases/download/latest/p5jsMode.txt should be copied to https://github.com/fathominfo/processing-p5js-mode/releases/download/latest/p5jsMode.zip/mode.properties with each new release.

So… something to fix on the next release.

**Comment by benfry** [comment]
Should be fixed in 1.0.3.
