### ISSUE TITLE
p5js mode seems to be making unsolicited changes to my index.html file

### ISSUE THREAD

**Issue by Antony74** [fathominfo/processing-p5js-mode#13]
p5js mode seems to be making unsolicited changes to my index.html file.  Please see this commit as an example of this behaviour - I'd only intended to change a src attribute, but rather a lot else seems to have been changed on my behalf.

https://github.com/Antony74/hyperbolic/commit/fcc3196e12bcde4a77dddf00f7b2ff74542dbc93

I think part of the problem is that JSoup's "prettyPrint" mode is on by default.  It's much like PDE's very nice Edit->Auto Format, menu-item, but mandatory, and every time you save.

However, all that extra vertical whitespace in the <style> tag is possibly because I'm running Windows, which uses carriage-return-line-feed (\r\n) instead of the otherwise universal line-feed (\n)? :-(

In which case, and very tentatively, a fix might look something like this? d303a5a6749e5ee392c25717559ab9aaa165c287 but without in-depth knowledge of the code, all I can say is it works for me.

**Comment by benfry** [comment]
Sorry about that, and thanks for looking into it. Your commit makes sense and I've added that for the next release.

**Comment by benfry** [comment]
Opting to instead revert back to the old method of inserting HTML for the next release. We may bring back this fancier stuff at some point, but too many other bugs have been found in the meantime.
