### ISSUE TITLE
Add support for editing .json files in the Editor

### ISSUE THREAD

**Issue by FjelletsEkko** [fathominfo/processing-p5js-mode#16]
I am failing to create a .json-tab in Processing 3.3 with "p5.js"-mode and get the error '".json" is not a valid extension', but I do not have a problem with loading a .json-file created elsewhere.

**Comment by benfry** [comment]
Are you using the latest version?

**Comment by FjelletsEkko** [comment]
Yes: "p5.js Mode 1.0.4 Fathom Information Design"

**Comment by benfry** [comment]
Oh… Sorry, I misread the error report. p5jsMode doesn't support editing .json files as part of the editor. I'll mark this as an enhancement.

**Comment by FjelletsEkko** [comment]
Gotcha. Good to know!

**Comment by benfry** [comment]
Fixed for the next release (1.1). `.json` files will need to be in the root of the sketch folder (not a subfolder like `data` or `assets`) and they'll be visible.
