### ISSUE TITLE
p5.js mode PDE editor bugs when editing a .css file

### ISSUE THREAD

**Issue by Wildernesss** [fathominfo/processing-p5js-mode#21]
Hi everyone. I know that p5.js mode for PDE is not a developping tools. But even with this in mind, I think that solving what seems to be a minor bug could provide additionnal motivation to students or people discovering interactive visual programming with web programming using Javascript, HMTL and CSS, To be short, there is apparently a bug in p5.js PDE editor when editing a simpe .css file. See issue reported to 

[](https://github.com/processing/processing/issues/5628)

Ben Fry suggested to report this issue here and closed the #5628 issue.

If a fix could be found without too much work, it would be great!

Thanks a lot for great development work.  Processing is really a great tool for programming learning!

Laurent

**Comment by benfry** [comment]
Thanks for the report! Will try to take a look when we have a chance to work on this project. (And others are welcome to contribute a fix.)

**Comment by benfry** [comment]
This was actually a bug inside the PDE code, which is now fixed for Processing 3.5.3.
