### ISSUE TITLE
p5.js PDE editor mode doesn't recognize class operator in a separate js file (when saved)

### ISSUE THREAD

**Issue by alana92** [fathominfo/processing-p5js-mode#23]
When I create a class and run it (without saving) the sketch works fine, but when I save it and try to run the sketch again it throws the follow error on the js file with the class:

`SyntaxError: Expected an operand but found class
`

**Comment by alana92** [comment]
> When I create a class in a separate javascript file that I reference in the main sketch and run it (without saving) the sketch works fine, but when I save it and try to run the sketch again it throws the follow error on the js file with the class:
> 
> SyntaxError: Expected an operand but found class
> 
> It does however work if I save the code for the class in the same js file (the main sketch file).

**Comment by benfry** [comment]
Give this a try with the new version (1.2) that I just posted. It should be working now.

**Comment by alana92** [comment]
Thanks Ben, it works great.
