### ISSUE TITLE
Could not download in mode in Processing

### ISSUE THREAD

**Issue by DohrliOfDeath** [fathominfo/processing-p5js-mode#24]
Steps to reproduce:
Open Processing
Start Tool/Mode/Library/Example Manager
Press  Modes
Press p5js Mode
Press Install

> Could not download https://github.com/fathominfo/processing-p5js-mode/releases/download/latest/p5jsMode.zip to /tmp/download3432778025560692869p5jsMode.zip : Error during download and install of p5.js Mode.

This is the error, if I try and download the above link with wget, I get a 404 Error. 

Processing 3.5.4-1 install with pacman (Arch Linux)

**Comment by benfry** [comment]
That URL is working fine from here… perhaps there's something blocking Github downloads on your end?

**Comment by DohrliOfDeath** [comment]
Checked it again, it somehow works now, I guess this is closed then, thanks anyway
