### ISSUE TITLE
Windows temp files still in use and cannot be removed

### ISSUE THREAD

**Issue by benfry** [fathominfo/processing-p5js-mode#6]
`cleanTempFiles()` is failing on some Windows machines. Also appears to be locking up the PDE (even though the exception is caught/printed/ignored).

**Comment by benfry** [comment]
It's not a problem that the temp files aren't being removed (it can fail silently), and we can just re-try the next time the sketch runs. However, the locking up or failing to continue after the exception is a real problem.

**Comment by benfry** [comment]
Should be fixed for 1.0.3.

**Comment by inkwellsiesta** [comment]
Cannot replicate, closing issue.
