### ISSUE TITLE
Opening a sketch without PDE folder structure not working properly

### ISSUE THREAD

**Issue by benfry** [fathominfo/processing-p5js-mode#7]
It's properly putting up the "create the folder, move the sketch, and continue?" message but there seems to be something wrong with the renaming.

**Comment by inkwellsiesta** [comment]
This was disabled in https://github.com/fathominfo/processing-p5js-mode/commit/b1f721915ce60b979d75f5f9acdbff0515c0a8ba, and now it no longer tries to rename the js file.

**Comment by benfry** [comment]
See also https://github.com/fathominfo/processing-p5js-mode/issues/14
