### ISSUE TITLE
re-use port and server instance

### ISSUE THREAD

**Issue by benfry** [fathominfo/processing-p5js-mode#8]
Or at least make this an option...

**Comment by benfry** [comment]
In the initial release, felt that it was more confusing to have "port in use" errors being thrown (and trickier to catch 'em all) if the server got into a weird state vs. the tradeoff of having new port numbers showing up in new tabs (which also helps with caching). 

We should keep the old random port logic (in case we need to go back), but instead switch to using a fixed port and a single server that stays running (and if need be, we can add an option to explicitly restart it).

**Comment by inkwellsiesta** [comment]
Addressed in https://github.com/fathominfo/processing-p5js-mode/commit/aa77a3903691b4a678eacddfd6dcb3cea592c289.

As of now, no option to explicitly restart.

**Comment by benfry** [comment]
Opting to re-use the port per sketch window, but not on each Run.
